services:
  - type: web
    name: elephant-id-app
    env: python
    buildCommand: |
      mkdir -p models
      curl -L "https://drive.google.com/uc?export=download&id=1ljOG8mPgQ7fQuq66Dh_oeuUwjjGMGD2W" -o models/best_model.pth
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    plan: free
